[workspace]
channels = ["conda-forge", "https://conda.anaconda.org/hcc"]
name = "anchored_docking_workflow"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
dock = "python generate_slurm.py"

[activation.env]
PATH = "$CONDA_PREFIX/bin:$PWD/scripts:$PATH"

[dependencies]
rdkit = ">=2025.9.5,<2026"
meeko = "==0.6.1"
python = ">=3.9"
